"""add article external id

Revision ID: 8077f47ecd2c
Revises: b01dc46eca1c
Create Date: 2026-06-08 18:03:29.974419

"""
from collections.abc import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8077f47ecd2c'
down_revision: Union[str, Sequence[str], None] = 'b01dc46eca1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index('ix_articles_source_external_id', 'articles', ['source', 'external_id'], unique=False)
    op.create_unique_constraint('uq_articles_source_external_id', 'articles', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_articles_source_external_id', 'articles', type_='unique')
    op.drop_index('ix_articles_source_external_id', table_name='articles')
    op.drop_column('articles', 'external_id')
    # ### end Alembic commands ###
