"""create initial tables

Revision ID: b01dc46eca1c
Revises: 
Create Date: 2026-05-14 20:36:08.746397

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b01dc46eca1c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("embedding_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_articles_url"), "articles", ["url"], unique=True)
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("artifact_uri", sa.String(length=1000), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_versions_name"), "model_versions", ["name"], unique=False)
    op.create_index(op.f("ix_model_versions_version"), "model_versions", ["version"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_external_id"), "users", ["external_id"], unique=True)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "article_id", "model_version", name="uq_recommendation"),
    )
    op.create_index(
        op.f("ix_recommendations_article_id"),
        "recommendations",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_model_version"),
        "recommendations",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_user_id"),
        "recommendations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_events_article_id"), "user_events", ["article_id"], unique=False)
    op.create_index(op.f("ix_user_events_event_type"), "user_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_user_events_timestamp"), "user_events", ["timestamp"], unique=False)
    op.create_index(op.f("ix_user_events_user_id"), "user_events", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_events_user_id"), table_name="user_events")
    op.drop_index(op.f("ix_user_events_timestamp"), table_name="user_events")
    op.drop_index(op.f("ix_user_events_event_type"), table_name="user_events")
    op.drop_index(op.f("ix_user_events_article_id"), table_name="user_events")
    op.drop_table("user_events")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_model_version"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_article_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_users_external_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_model_versions_version"), table_name="model_versions")
    op.drop_index(op.f("ix_model_versions_name"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_articles_url"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
